Update puzzle.py
ustymhentosh/Puzzle pull request #7
Opened 2023-02-16 13:51 UTC by ustymhentosh

Beautifying

2023-02-17 09:38 UTC, kostyantynHrytsyuk requested changes
Майже все добре

Лише один коментар дав прямо в коді

І ще маю питання по файлу row

Я ніяк не бачу потреби в ньому.
Тому або поясніть для чого він або видаліть його з репозиторію

Коли це зробите - одразу виставлю оцінки

Новий pull request створювати не треба, я буду бачити зміни прямо тут

2023-02-17 09:38 UTC, kostyantynHrytsyuk commented on puzzle.py
>              if j != '*' and j != ' ':
Тут pylint підказує що можна зробити спрощення і використати оператор in

2023-02-17 10:16 UTC, ustymhentosh commented on puzzle.py
>              if j != '*' and j != ' ':
![image_2023-02-17_12-13-07](https://user-images.githubusercontent.com/116552529/219616279-0622ef50-e246-448c-a3c7-8f714eb018b4.png)

У нас показує, що ця помилка вже виправлена у цьому pull request

2023-02-18 14:46 UTC, kostyantynHrytsyuk approved these changes
Більше в мене зауважень немає
Завдання виконано, зараз виставлю оцінки команді

Можете робити pull request

Успіхів!

2023-02-18 14:46 UTC, kostyantynHrytsyuk commented on puzzle.py
>              if j != '*' and j != ' ':
На скріншоті, що Ви надіслали чітко видно, що саме цей рядок (31 на зображенні ліворуч, 38 на зображенні праворуч) ніяк не змінений

Але це виправлення є дуже дрібним і ніяк не впливає на результат.
Тому я закрию цей коментар

2023-02-18 14:49 UTC, merged